#server.port= 8761
#spring.application.name= discoveryregistry
# 
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#
#logging.level.com.netflix.eureka= off
#logging.level.com.netflix.discovery=off

server:
 port: 8890

    
spring:
  profiles:
    active: native
  application:
    name: config-server  
 
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
          
eureka:
  client:
   serviceUrl:
     defaultZone: http://172.23.238.190:8761/eureka
     
#eureka:
#  client:
#   serviceUrl:
#     defaultZone: http://192.168.1.4:8761/eureka     